# Generated by Django 2.0 on 2018-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'waiting'), (1, 'approved'), (2, 'completed')], default=0, verbose_name='Status'),
        ),
    ]
