# Generated by Django 2.0 on 2018-09-17 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180917_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 0, 37, 44, 8549, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
