# Generated by Django 2.0 on 2018-09-19 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180917_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 11, 7, 11, 529376, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
