# Generated by Django 2.0 on 2018-09-19 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180919_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 11, 33, 6, 413024, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
