# Generated by Django 2.0 on 2018-09-19 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180919_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 12, 30, 36, 28558, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
