# Generated by Django 2.0 on 2018-09-19 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180919_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 21, 51, 50, 973637, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
