# Generated by Django 2.0 on 2018-09-19 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180920_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 22, 56, 21, 917940, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
