# Generated by Django 2.0 on 2018-09-23 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180920_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 17, 28, 37, 344447, tzinfo=utc), verbose_name='Key validity'),
        ),
    ]
