# Generated by Django 2.0 on 2018-09-19 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rank_item', '0004_auto_20180920_0051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Update date')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank_item.Company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
