# Generated by Django 2.0 on 2018-09-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Update date')),
                ('name', models.CharField(max_length=128, verbose_name='Company name')),
                ('region', models.PositiveSmallIntegerField(choices=[(0, ''), (1, 'Санкт-Петербург'), (2, 'Москва')], default=0, verbose_name='Region')),
                ('type', models.CharField(max_length=255, verbose_name='Вид деятельности')),
                ('site', models.CharField(max_length=128, verbose_name='Сайт')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Update date')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, ''), (1, 'Категория 1'), (2, 'Категория 2')], default=0, verbose_name='Category name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank_item.CompanyCategory', verbose_name='Category'),
        ),
    ]
