# Generated by Django 2.0 on 2018-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(max_length=128, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='companycategory',
            name='name',
            field=models.CharField(default=0, max_length=128, verbose_name='Category name'),
        ),
    ]
