# Generated by Django 2.0 on 2018-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_item', '0003_auto_20180919_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='company',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
